name: Omnilogi

services:
  db-mysql:
    image: mysql:8.0.46
    container_name: Omnilogi
    restart: always
    environment:
      - MYSQL_DATABASE=Omnilogi
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - Omnilogi-data:/var/lib/mysql
volumes:
 Omnilogi-data: